Repository dseinternational/open-dotnet, pull requests merged in 2024-01, with the labels that each got.

#78 Document and test PaginationOptions
  DSE.Open.sln
  src/DSE.Open.Abstractions/PaginationOptions.cs
  src/DSE.Open.Results/Pagination.cs
  test/DSE.Open.Abstractions.Tests/DSE.Open.Abstractions.Tests.csproj
  test/DSE.Open.Abstractions.Tests/PaginationOptionsTests.cs
  test/DSE.Open.Abstractions.Tests/xunit.runner.json
Labels: documentation

#81 Use short-circuiting or in IsLetterOrDigit
  src/DSE.Open/AsciiChar.Helpers.cs
Labels: enhancement

#83 Allow Pagination.None when result contains error notifications
  src/DSE.Open.Results/PaginatedCollectionValueAsyncResultBuilder.cs
  src/DSE.Open.Results/PaginatedCollectionValueResultBuilder.cs
Labels: bug

#92 Math functions (experimental)
  DSE.Open.sln
  Directory.Packages.props
  NuGet.config
  benchmarks/DSE.Open.Benchmarks/DSE.Open.Benchmarks.csproj
  benchmarks/DSE.Open.Benchmarks/Numerics/SequenceSumBenchmarksBase.cs
  benchmarks/DSE.Open.Benchmarks/Numerics/SequenceSumDoubleBenchmarks.cs
  benchmarks/DSE.Open.Benchmarks/Numerics/SequenceSumFloatingPointBenchmarksBase.cs
  benchmarks/DSE.Open.Benchmarks/Numerics/SequenceSumFloatingPointKahanBabushkaNeumaierBenchmarks.cs
  benchmarks/DSE.Open.Benchmarks/Numerics/SequenceSumInt64Benchmarks.cs
  benchmarks/DSE.Open.Benchmarks/Numerics/SequenceSumIntBenchmarks.cs
  benchmarks/DSE.Open.Benchmarks/Numerics/SequenceSumIntegerBenchmarksBase.cs
  benchmarks/DSE.Open.Benchmarks/Numerics/SequenceSumSingleBenchmarks.cs
  src/DSE.Open.Numerics/DSE.Open.Numerics.csproj
  src/DSE.Open.Numerics/EmptySequenceException.cs
  src/DSE.Open.Numerics/MedianMethod.cs
  src/DSE.Open.Numerics/NumericsException.cs
  src/DSE.Open.Numerics/Sequence.GeometricMean.cs
  src/DSE.Open.Numerics/Sequence.HarmonicMean.cs
  src/DSE.Open.Numerics/Sequence.Maximum.cs
  src/DSE.Open.Numerics/Sequence.Mean.cs
  src/DSE.Open.Numerics/Sequence.Median.cs
  src/DSE.Open.Numerics/Sequence.Minimum.cs
  src/DSE.Open.Numerics/Sequence.Mode.cs
  src/DSE.Open.Numerics/Sequence.PopulationStandardDeviation.cs
  src/DSE.Open.Numerics/Sequence.PopulationVariance.cs
  src/DSE.Open.Numerics/Sequence.Quantiles.cs
  src/DSE.Open.Numerics/Sequence.StandardDeviation.cs
  src/DSE.Open.Numerics/Sequence.Sum.cs
  src/DSE.Open.Numerics/Sequence.Variance.cs
  src/DSE.Open.Numerics/SummationCompensation.cs
  src/DSE.Open/Collections/Generic/ReadOnlyValueCollection{T}.cs
  src/DSE.Open/Linq/EnumerableExtensions.cs
  test/DSE.Open.Numerics.Tests/DSE.Open.Numerics.Tests.csproj
  test/DSE.Open.Numerics.Tests/SequenceTests.GeometricMean.cs
  test/DSE.Open.Numerics.Tests/SequenceTests.HarmonicMean.cs
  test/DSE.Open.Numerics.Tests/SequenceTests.Maximum.cs
  test/DSE.Open.Numerics.Tests/SequenceTests.Mean.cs
  test/DSE.Open.Numerics.Tests/SequenceTests.Minimum.cs
  test/DSE.Open.Numerics.Tests/SequenceTests.Mode.cs
  test/DSE.Open.Numerics.Tests/SequenceTests.Quantiles.cs
  test/DSE.Open.Numerics.Tests/SequenceTests.StandardDeviation.cs
  test/DSE.Open.Numerics.Tests/SequenceTests.Sum.cs
  test/DSE.Open.Numerics.Tests/SequenceTests.Variance.cs
Labels: area-numerics

#95 Remove _isInitialized from generated value types
  gen/DSE.Open.Values.Generators/Model/ValueTypeSpec.cs
  gen/DSE.Open.Values.Generators/ValueTypesGenerator.Emitter.cs
  gen/DSE.Open.Values.Generators/ValueTypesGenerator.cs
  src/DSE.Open.DomainModel/Entities/EntityDataInitializationHelper.cs
  src/DSE.Open.Globalization/LanguageTag.cs
  src/DSE.Open.Observations.Abstractions/YesNo.cs
  src/DSE.Open.Observations.Abstractions/YesNoUnsure.cs
  src/DSE.Open.Speech.Abstractions/SpeechSound.cs
  src/DSE.Open.Values.Abstractions/IValue.cs
  src/DSE.Open.Values.Abstractions/UninitializedValueException.cs
  src/DSE.Open.Values.Abstractions/ValueAttribute.cs
  src/DSE.Open.Values/AlphaCode.cs
  src/DSE.Open.Values/AlphaNumericCode.cs
  src/DSE.Open.Values/DSE.Open.Values.csproj
  src/DSE.Open.Values/Identifier.cs
  src/DSE.Open.Values/Label.cs
  src/DSE.Open.Values/Tag.cs
  src/DSE.Open.Values/Text/Json/Serialization/JsonInt32ValueConverter.cs
  src/DSE.Open.Values/UriAsciiPath.cs
  src/DSE.Open.Values/UriPath.cs
  test/DSE.Open.Values.Generators.Tests/DSE.Open.Values.Generators.Tests.csproj
  test/DSE.Open.Values.Generators.Tests/NominalValueTypeGenerationTests.cs
  test/DSE.Open.Values.TestValues/DSE.Open.Values.TestValues.csproj
  test/DSE.Open.Values.Tests/LabelTests.cs
  version.json
  version.props
Labels: area-values
