Repository dseinternational/open-dotnet, pull requests merged in 2024-02, with the labels that each got.

#99 More numerics experimenting
  DSE.Open.sln
  Directory.Packages.props
  src/DSE.Open.Interop.Torch/Class1.cs
  src/DSE.Open.Interop.Torch/DSE.Open.Interop.Torch.csproj
  src/DSE.Open.Numerics/GuardSequence.cs
  src/DSE.Open.Numerics/IReadOnlyVector.cs
  src/DSE.Open.Numerics/IVector.cs
  src/DSE.Open.Numerics/Matrix.T.cs
  src/DSE.Open.Numerics/Matrix.cs
  src/DSE.Open.Numerics/NumericsException.cs
  src/DSE.Open.Numerics/ReadOnlySpanVector.cs
  src/DSE.Open.Numerics/ReadOnlyVector.T.cs
  src/DSE.Open.Numerics/ReadOnlyVector.cs
  src/DSE.Open.Numerics/Sequence.Add.cs
  src/DSE.Open.Numerics/Sequence.Multiply.cs
  src/DSE.Open.Numerics/Sequence.Subtract.cs
  src/DSE.Open.Numerics/SpanVector.cs
  src/DSE.Open.Numerics/Vector.T.cs
  src/DSE.Open.Numerics/Vector.cs
  test/DSE.Open.Interop.Torch.Tests/DSE.Open.Interop.Torch.Tests.csproj
  test/DSE.Open.Interop.Torch.Tests/Smoketest.cs
  test/DSE.Open.Numerics.Tests/ReadOnlyVectorTests.cs
  test/DSE.Open.Numerics.Tests/VectorTests.cs
Labels: area-numerics

#98 Refactor MemoryExtensions to reduce duplication
  src/DSE.Open/MemoryExtensions.AsciiChar.cs
  src/DSE.Open/MemoryExtensions.Byte.cs
  src/DSE.Open/MemoryExtensions.Char.cs
  src/DSE.Open/MemoryExtensions.cs
  test/DSE.Open.Tests/MemoryExtensionsTests.cs
Labels: enhancement, area-core

#100 Allocation improvements for CharSequence
  src/DSE.Open/CharSequence.cs
  src/DSE.Open/CharSequenceExtensions.cs
Labels: area-values, performance
